# database_url="postgres://ivy:password@localhost/activityfun_dev"
instance_domain="place.ivytime.gay"
bind_address="127.0.0.1"
port=8020
contact_email="public.ivy.gifford@gmail.com"


# SERVER_ADDR="127.0.0.1:8080"
pg_user="ivy"
pg_password="password"
pg_host="127.0.0.1"
pg_port=5432
pg_dbname="mini_ap"
